
server {
    listen 8080;
    listen [::]:8080;

    server_name 221.121.3.208;

    root /var/www/devops-hackathon-de008-vuviettien/src;
    index index.html;

    access_log /var/log/nginx/tienvv-hnk24cntt4.access.log;
    error_log /var/log/nginx/tienvv-hnk24cntt4.error.log;

    location / {
        allow all;
        try_files $uri $uri/ =404;
    }
}
